### ISSUE TITLE
Architectural Questions about Isaura Repo

### ISSUE THREAD

**Issue by raul-bermejo** [ersilia-os/isaura#1] opened 2023-06-27 01:14 UTC
This issue is a placeholder to ask questions about architectural decisions for the Isaura repo, so GDI volunteers can better understand the rationale behind the architecture of the Isaura repo in order to build on top of it

**Comment by raul-bermejo** [comment] 2023-06-27 01:19
- What’s the rationale for choosing DynamoDB as a managed storage service as opposed to cheaper storage service e.g. S3 + AWS Glue / Athena? Optimisation?
- Did you consider fetching the models using Amazon ECS/ECR? I assume EOS didn’t have the models in Docker Hub yet
- What does the authentication look like in the [Isaura repo](https://github.com/ersilia-os/isaura)? Do users have both `SELECT` & `MODIFY` access to the DynamoDB database? 
- For the precalculation pipeline, did you think about using a cloud service like SageMaker or ECS for running the pipeline on a CI/CD fashion?
- Is the code in the Isaura repo integrated at all with the Ersilia API (`ersilia fetch`, `ersilia serve`, …)?

**Comment by leoank** [comment] 2023-06-29 02:24
> What’s the rationale for choosing DynamoDB as a managed storage service as opposed to cheaper storage service e.g. S3 + AWS Glue / Athena? Optimisation?

Isaura is described as a data lake which is currently a misnomer. It can be much better described as a cache because of the use case we were targeting when I designed the architecture.

Primary use case:
A user fetches the pre-calculated result for a specific molecule for a specific model. The result can change with model updates.

The queries that a user makes are `transactional` not `analytical`. So we decided on using an online transaction processing database(OLTP) DynamoDB rather than going with an online analytical processing system(OLAP) like S3 + AWS Glue/Athena.

I am also aware of the cost differences. We did some calculations based on our expected usage and found that using DynamoDB(for now) is more economical(mostly free).

But Isaura is designed to scale economically if needed. We can easily switch to self-hosted [ScyllaDB](https://www.scylladb.com/) clusters to control scaling costs whenever needed.

> Did you consider fetching the models using Amazon ECS/ECR? I assume EOS didn’t have the models in Docker Hub yet

The work on containerizing models and pushing them to the Docker Hub is ongoing. We have made good progress.
I don't think we considered using Amazon ECR or ECS because we want to control our costs. One of the reasons for choosing DockerHub was because they are sponsoring us as an Open source project.

> What does the authentication look like in the [Isaura repo](https://github.com/ersilia-os/isaura)? Do users have both SELECT & MODIFY access to the DynamoDB database?

Only Admins can access the database directly. The users access the database through a lambda function. The users only have read access to the database. The read API is publicly available without any authentication requirement. This is by design.

> For the precalculation pipeline, did you think about using a cloud service like SageMaker or ECS for running the pipeline on a CI/CD fashion?

We use Github actions extensively for our CI/CD needs. @miquelduranfrigola  was working on a project together with folks at GitHub to implement a precalculation pipeline with Github actions. I am not aware of the current status of the project. 

> Is the code in the Isaura repo integrated at all with the Ersilia API (ersilia fetch, ersilia serve, …)?

@miquelduranfrigola please help answer this. Also please correct my answers above if any of them are outdated.

**Comment by miquelduranfrigola** [comment] 2023-08-04 12:00
Hi @leoank and @raul-bermejo I am so sorry I completely overlooked this thread.

**Comment by miquelduranfrigola** [comment] 2023-12-21 17:08
I think all of this has been resolved nicely as reflected in the [model-inference-pipeline](https://github.com/ersilia-os/model-inference-pipeline) repository.

I am closing the issue for now. Please feel free to reopen it.

**Closed by miquelduranfrigola** 2023-12-21 17:08 UTC
